[package]
name = "sync_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
midir = "0.10"
crossterm = "0.27.0"
ratatui = "0.26.3"
anyhow = "1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
crossbeam-channel = "0.5"
time = "0.3"
utils = { path = "../utils" }